apps-script:
  label: Apps Script
  permalink: /apps-script
  description: Google Apps Script is a JavaScript-based language that lets you add functionality to Google Sheets, Docs, and Forms.

automation:
  label: Automation
  permalink: /automation
  description: Automate repetitive tasks to save time and reduce errors.

google-workspace:
  label: Google Workspace
  permalink: /google-workspace
  description: A suite of cloud-based productivity and collaboration tools from Google.

power-automate:
  label: Power Automate
  permalink: /power-automate
  description: Microsoft Power Automate is a cloud-based & desktop service that helps you automate workflows across your favorite apps and services.